version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booksdb
      MYSQL_USER: books
      MYSQL_PASSWORD: books
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
      MYSQL_HOST: db
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: booksdb
      MYSQL_USER: books
      MYSQL_PASSWORD: books
      MYSQL_PARAMS: "parseTime=true&charset=utf8mb4&loc=UTC"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dbdata:
